using System; 
{{
/*PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 1 AL 500
2. PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 500 AL 1
3. PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS IMPARES COMPRENDIDOS ENTRE EL 1 Y EL 100
4. PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 0 AL 1000, INCREMENTANDO DE 5 EN 5
5. PROGRAMA QUE PIDA AL USUARIO UN NUMERO, Y MUESTR EN PANTALLA LA SECUENCIA DESCENDENTE DESDE EL NUMERO INGRESADO HASTA 0
6. PROGRAMA QUE PIDA AL USUARIO UN NUMERO. EL NUMERO RECIBIDO LO MULTIPLICARA POR 5. SI EL RESULTADO ES UN NUMERO PAR, MOSTRARA EN PANTALLA LA SECUENCIA ASCENDENTE DESDE EL NUMERO RECIBIDO HASTA EL RESULTADO DE LA MULTIPLICACION. EN CASO CONTRARIO, MOSTRARA LA SECUENCIA DESCENDENTE DESDE EL RESULTADO DE LA MULTIPLICACION HASTA EL NUMERO INGRESADO.
7. PROGRAMA QUE PIDA AL USUARIO DOS NUMERO. SI EL 1ER NUMERO ES MAYOR QUE EL SEGUNDO, MOSTRARA LA SECUENCIA DESCENDENTE DESDE EL PRIMER NUMERO HASTA EL SEGUNDO, EN CASO CONTRARIO MOSTRAR LA SECUENCIA ASCENDENTE.*/



//while(1 == 1)

Console.WriteLine(@"¿Que quieres hacer? 
1. PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 1 AL 500
2. PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 500 AL 1
3. PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS IMPARES COMPRENDIDOS ENTRE EL 1 Y EL 100
4. PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 0 AL 1000, INCREMENTANDO DE 5 EN 5
5. PROGRAMA QUE PIDA AL USUARIO UN NUMERO, Y MUESTR EN PANTALLA LA SECUENCIA DESCENDENTE DESDE EL NUMERO INGRESADO HASTA 0
6. PROGRAMA QUE PIDA AL USUARIO UN NUMERO. EL NUMERO RECIBIDO LO MULTIPLICARA POR 5. SI EL RESULTADO ES UN NUMERO PAR, MOSTRARA EN PANTALLA LA SECUENCIA ASCENDENTE DESDE EL NUMERO RECIBIDO HASTA EL RESULTADO DE LA MULTIPLICACION. EN CASO CONTRARIO, MOSTRARA LA SECUENCIA DESCENDENTE DESDE EL RESULTADO DE LA MULTIPLICACION HASTA EL NUMERO INGRESADO.
7. PROGRAMA QUE PIDA AL USUARIO DOS NUMERO. SI EL 1ER NUMERO ES MAYOR QUE EL SEGUNDO, MOSTRARA LA SECUENCIA DESCENDENTE DESDE EL PRIMER NUMERO HASTA EL SEGUNDO, EN CASO CONTRARIO MOSTRAR LA SECUENCIA ASCENDENTE.");
int Val = int.Parse(Console.ReadLine());
Console.Clear(); 



if (Val == 1)

{
    //PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 1 AL 500
    Console.WriteLine("PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 1 AL 500");
    int Valor = 1; int Num = 0;
    while (Valor <= 500)
    {
        Valor ++;
        Num ++; 

        Console.WriteLine(Num + ""); 

    }
}

if (Val == 2)
{
    //PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 500 AL 1
    Console.WriteLine("PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 500 AL 1");
    int Valor = 1; //int Num =  0, 
    int Dat=500; 
    while (Valor != 500)
    {
        
        Valor  ++;
        //Num  --; 
        Dat= Dat -1; 
        
        //Num = (-1 * Num); 

        Console.WriteLine(Dat + "");
    }
}

if (Val == 3)
{
    //PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS IMPARES COMPRENDIDOS ENTRE EL 1 Y EL 100
    Console.WriteLine("PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS IMPARES COMPRENDIDOS ENTRE EL 1 Y EL 100");
    int Valor = 0; int Num = -1;
    while (Valor <= 100)
    {
        Valor = Valor +1;
        Num ++; 
        if (Num % 2 == 0)
        {
            Console.WriteLine(Num + " par");
        }
        else 
        {
            Console.WriteLine(Num + " impar");
        }

        
    }
}

if (Val == 4)
{
    //PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 0 AL 1000, INCREMENTANDO DE 5 EN 5
    Console.WriteLine("PROGRAMA QUE MUESTRE EN PANTALLA LOS NUMEROS DEL 0 AL 1000, INCREMENTANDO DE 5 EN 5");
    int Valor = 1; int Num = 0;
    while (Valor <= 200)
    {
        Valor ++;
        Num = Num + 5; 

        Console.WriteLine(Num + ""); 

    }

}

if (Val == 5)
{
    int Nom, Nom1;
    //PROGRAMA QUE PIDA AL USUARIO UN NUMERO, Y MUESTR EN PANTALLA LA SECUENCIA DESCENDENTE DESDE EL NUMERO INGRESADO HASTA 0
    Console.WriteLine("PROGRAMA QUE PIDA AL USUARIO UN NUMERO, Y MUESTR EN PANTALLA LA SECUENCIA DESCENDENTE DESDE EL NUMERO INGRESADO HASTA 0");
    Console.Write("Ingrese un numero: "); 
    Nom = int.Parse(Console.ReadLine()); 
    Nom1 = Nom;
    while (Nom != 0 )
    {
        Nom = Nom -1;  
        Console.WriteLine(Nom); 
    }
}

if (Val == 6)
{
    /*PROGRAMA QUE PIDA AL USUARIO UN NUMERO. EL NUMERO
    RECIBIDO LO MULTIPLICARA POR 5. SI EL RESULTADO ES 
    UN NUMERO PAR, MOSTRARA EN PANTALLA LA SECUENCIA 
    ASCENDENTE DESDE EL NUMERO RECIBIDO HASTA EL RESULTADO 
    DE LA MULTIPLICACION. EN CASO CONTRARIO, MOSTRARA LA SECUENCIA 
    DESCENDENTE DESDE EL RESULTADO DE LA MULTIPLICACION HASTA EL 
    NUMERO INGRESADO.*/
    Console.WriteLine(
    @"PROGRAMA QUE PIDA AL USUARIO UN NUMERO. EL NUMERO
    RECIBIDO LO MULTIPLICARA POR 5. SI EL RESULTADO ES 
    UN NUMERO PAR, MOSTRARA EN PANTALLA LA SECUENCIA 
    ASCENDENTE DESDE EL NUMERO RECIBIDO HASTA EL RESULTADO 
    DE LA MULTIPLICACION. EN CASO CONTRARIO, MOSTRARA LA SECUENCIA 
    DESCENDENTE DESDE EL RESULTADO DE LA MULTIPLICACION HASTA EL 
    NUMERO INGRESADO.");

    int Nom, Num1;
    Console.Write("Ingrese un numero: "); 
    Nom = int.Parse(Console.ReadLine()); 
    Num1 = Nom * 5; 

    if (Nom % 2 == 0 )
    {
     
        while (Nom != Num1 )
        {
            Nom = Nom + 1;
            Console.WriteLine(Nom);
        }
    }


    else 
    {
        while (Nom != Num1 )
        {
            Num1= Num1 - 1;
            Console.WriteLine(Num1);
        }
    }
    

}

if (Val == 7)
{

    /*PROGRAMA QUE PIDA AL USUARIO DOS NUMERO. SI EL 1ER
    NUMERO ES MAYOR QUE EL SEGUNDO, MOSTRARA LA SECUENCIA 
    DESCENDENTE DESDE EL PRIMER NUMERO HASTA EL SEGUNDO, 
    EN CASO CONTRARIO MOSTRAR LA SECUENCIA ASCENDENTE.*/
    Console.WriteLine(
    @"PROGRAMA QUE PIDA AL USUARIO DOS NUMERO. SI EL 1ER
    NUMERO ES MAYOR QUE EL SEGUNDO, MOSTRARA LA SECUENCIA 
    DESCENDENTE DESDE EL PRIMER NUMERO HASTA EL SEGUNDO, 
    EN CASO CONTRARIO MOSTRAR LA SECUENCIA ASCENDENTE.");

    int A, B;
    Console.Write("Ingrese un numero: ");
    A = int.Parse(Console.ReadLine());
    Console.Write("Ingrese un numero: ");
    B = int.Parse(Console.ReadLine());
    Console.Clear(); 
    if (A > B)
    {
        Console.WriteLine(A);
        while(A != B)
        {
            A = A - 1; 
            Console.WriteLine(A);
        }

    }
    else
    {
        
       //Console.WriteLine(B);
        while(B != A)
        {
            A = A + 1; 
            Console.WriteLine(A);
        }
    }
}

}}

